/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodbookingproject;


import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sujatha
 */
public class NewJFrame8 extends javax.swing.JFrame {
 double firstnum;   








   /**
     * Creates new form NewJFrame8
     */
    public NewJFrame8() {
        initComponents();
        INFO.setBounds(500,100,500,600);
        DRINKBOX.setBounds(500,100,500,600);
         
 
            
        
                                                             }
public NewJFrame8(String usernm) {initComponents();labelname.setText("WELCOME "+usernm+" PLEASE PLACE YOUR ORDER");
xtext.setText(usernm);xtext.setVisible(false);}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INFO = new javax.swing.JFrame();
        infoname = new javax.swing.JLabel();
        infouserid = new javax.swing.JLabel();
        infonumber = new javax.swing.JLabel();
        infoaddress = new javax.swing.JLabel();
        infocity = new javax.swing.JLabel();
        infopincode = new javax.swing.JLabel();
        DRINKBOX = new javax.swing.JFrame();
        rt2 = new javax.swing.JTextField();
        rt3 = new javax.swing.JTextField();
        rt4 = new javax.swing.JTextField();
        rc1 = new javax.swing.JCheckBox();
        rt5 = new javax.swing.JTextField();
        rc2 = new javax.swing.JCheckBox();
        rt6 = new javax.swing.JTextField();
        rc3 = new javax.swing.JCheckBox();
        rc4 = new javax.swing.JCheckBox();
        rc5 = new javax.swing.JCheckBox();
        rc6 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        rt1 = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        VEGBOX = new javax.swing.JFrame();
        gc5 = new javax.swing.JCheckBox();
        gc6 = new javax.swing.JCheckBox();
        gt1 = new javax.swing.JTextField();
        gt4 = new javax.swing.JTextField();
        gt5 = new javax.swing.JTextField();
        gt6 = new javax.swing.JTextField();
        gc1 = new javax.swing.JCheckBox();
        gt3 = new javax.swing.JTextField();
        gc2 = new javax.swing.JCheckBox();
        gt2 = new javax.swing.JTextField();
        gc3 = new javax.swing.JCheckBox();
        gc4 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        NONVEGBOX = new javax.swing.JFrame();
        nc1 = new javax.swing.JCheckBox();
        nt3 = new javax.swing.JTextField();
        nc2 = new javax.swing.JCheckBox();
        nt2 = new javax.swing.JTextField();
        nc3 = new javax.swing.JCheckBox();
        nc4 = new javax.swing.JCheckBox();
        nc5 = new javax.swing.JCheckBox();
        nc6 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        nt1 = new javax.swing.JTextField();
        nt4 = new javax.swing.JTextField();
        nt5 = new javax.swing.JTextField();
        nt6 = new javax.swing.JTextField();
        jToggleButton10 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        labelname = new javax.swing.JLabel();
        pa4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        tt2 = new javax.swing.JTextField();
        tt3 = new javax.swing.JTextField();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        pa5 = new javax.swing.JTextArea();
        jToggleButton9 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        xtext = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        INFO.setLocation(new java.awt.Point(500, 100));
        INFO.setMaximizedBounds(new java.awt.Rectangle(200, 200, 500, 700));
        INFO.setMinimumSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout INFOLayout = new javax.swing.GroupLayout(INFO.getContentPane());
        INFO.getContentPane().setLayout(INFOLayout);
        INFOLayout.setHorizontalGroup(
            INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INFOLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoname, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infouserid, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infonumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infocity, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infopincode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        INFOLayout.setVerticalGroup(
            INFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(INFOLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(infoname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(infouserid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(infonumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(infoaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(infocity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(infopincode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DRINKBOX.setLocation(new java.awt.Point(400, 100));
        DRINKBOX.setMinimumSize(new java.awt.Dimension(835, 535));
        DRINKBOX.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rt2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rt2.setText("0");
        DRINKBOX.getContentPane().add(rt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 400, -1));

        rt3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rt3.setText("0");
        DRINKBOX.getContentPane().add(rt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 400, -1));

        rt4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rt4.setText("0");
        DRINKBOX.getContentPane().add(rt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 400, -1));

        rc1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rc1.setForeground(new java.awt.Color(255, 255, 255));
        rc1.setText("APPLE JUICE 100RS");
        rc1.setOpaque(false);
        DRINKBOX.getContentPane().add(rc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        rt5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rt5.setText("0");
        DRINKBOX.getContentPane().add(rt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 400, -1));

        rc2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rc2.setForeground(new java.awt.Color(255, 255, 255));
        rc2.setText("MANGO MILK SHAKE 100RS");
        rc2.setOpaque(false);
        DRINKBOX.getContentPane().add(rc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 23));

        rt6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rt6.setText("0");
        DRINKBOX.getContentPane().add(rt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 400, -1));

        rc3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rc3.setForeground(new java.awt.Color(255, 255, 255));
        rc3.setText("STRAWBERRY MILK SHAKE 100RS");
        rc3.setOpaque(false);
        DRINKBOX.getContentPane().add(rc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        rc4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rc4.setForeground(new java.awt.Color(255, 255, 255));
        rc4.setText("FANTA 0.5 LITRE 50RS");
        rc4.setOpaque(false);
        DRINKBOX.getContentPane().add(rc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        rc5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rc5.setForeground(new java.awt.Color(255, 255, 255));
        rc5.setText("MAZZA 0.5 LITRE 50RS");
        rc5.setOpaque(false);
        DRINKBOX.getContentPane().add(rc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 234, -1));

        rc6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rc6.setForeground(new java.awt.Color(255, 255, 255));
        rc6.setText("COCACOLA 0.5 LITRE 50RS");
        rc6.setOpaque(false);
        DRINKBOX.getContentPane().add(rc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SELECT QUANTITY");
        DRINKBOX.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 390, -1));

        rt1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        rt1.setText("0");
        DRINKBOX.getContentPane().add(rt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 400, -1));

        jToggleButton3.setText("DONE");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        DRINKBOX.getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 112, 40));
        DRINKBOX.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 500));

        VEGBOX.setLocation(new java.awt.Point(500, 100));
        VEGBOX.setMinimumSize(new java.awt.Dimension(600, 425));
        VEGBOX.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gc5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gc5.setForeground(new java.awt.Color(255, 255, 255));
        gc5.setText("VEG BURGER 75RS");
        gc5.setOpaque(false);
        VEGBOX.getContentPane().add(gc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 269, -1));

        gc6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gc6.setForeground(new java.awt.Color(255, 255, 255));
        gc6.setText("VEG ROLL 75RS");
        gc6.setOpaque(false);
        VEGBOX.getContentPane().add(gc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 269, -1));

        gt1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gt1.setText("0");
        VEGBOX.getContentPane().add(gt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 170, -1));

        gt4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gt4.setText("0");
        VEGBOX.getContentPane().add(gt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 170, -1));

        gt5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gt5.setText("0");
        VEGBOX.getContentPane().add(gt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 170, -1));

        gt6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gt6.setText("0");
        VEGBOX.getContentPane().add(gt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 170, -1));

        gc1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gc1.setForeground(new java.awt.Color(255, 255, 255));
        gc1.setText(" NOODLES 100RS");
        gc1.setOpaque(false);
        VEGBOX.getContentPane().add(gc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 269, -1));

        gt3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gt3.setText("0");
        VEGBOX.getContentPane().add(gt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 170, -1));

        gc2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gc2.setForeground(new java.awt.Color(255, 255, 255));
        gc2.setText(" FRIED RICE 125RS");
        gc2.setOpaque(false);
        VEGBOX.getContentPane().add(gc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 269, -1));

        gt2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gt2.setText("0");
        VEGBOX.getContentPane().add(gt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 170, -1));

        gc3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gc3.setForeground(new java.awt.Color(255, 255, 255));
        gc3.setText("VEG BIRIYANI 130RS");
        gc3.setOpaque(false);
        VEGBOX.getContentPane().add(gc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 269, -1));

        gc4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        gc4.setForeground(new java.awt.Color(255, 255, 255));
        gc4.setText("SCHEZWAN NOODLES 125RS");
        gc4.setOpaque(false);
        VEGBOX.getContentPane().add(gc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SELECT QUANTITY");
        VEGBOX.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jToggleButton4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jToggleButton4.setText("DONE");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        VEGBOX.getContentPane().add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 115, 35));
        VEGBOX.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 390));

        NONVEGBOX.setLocation(new java.awt.Point(500, 100));
        NONVEGBOX.setMinimumSize(new java.awt.Dimension(550, 425));
        NONVEGBOX.getContentPane().setLayout(null);

        nc1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nc1.setForeground(new java.awt.Color(255, 255, 255));
        nc1.setText("CHICKEN NOODLES 125RS");
        nc1.setOpaque(false);
        NONVEGBOX.getContentPane().add(nc1);
        nc1.setBounds(8, 47, 247, 29);

        nt3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nt3.setText("0");
        NONVEGBOX.getContentPane().add(nt3);
        nt3.setBounds(437, 130, 87, 27);

        nc2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nc2.setForeground(new java.awt.Color(255, 255, 255));
        nc2.setText("CHICKEN FRIED RICE 150RS");
        nc2.setOpaque(false);
        NONVEGBOX.getContentPane().add(nc2);
        nc2.setBounds(8, 87, 320, 29);

        nt2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nt2.setText("0");
        nt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt2ActionPerformed(evt);
            }
        });
        NONVEGBOX.getContentPane().add(nt2);
        nt2.setBounds(437, 88, 87, 27);

        nc3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nc3.setForeground(new java.awt.Color(255, 255, 255));
        nc3.setText("CHICKEN BIRIYANI 175RS");
        nc3.setOpaque(false);
        NONVEGBOX.getContentPane().add(nc3);
        nc3.setBounds(8, 128, 249, 29);

        nc4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nc4.setForeground(new java.awt.Color(255, 255, 255));
        nc4.setText("MUTTON BIRIYANI 180RS");
        nc4.setOpaque(false);
        NONVEGBOX.getContentPane().add(nc4);
        nc4.setBounds(8, 162, 251, 29);

        nc5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nc5.setForeground(new java.awt.Color(255, 255, 255));
        nc5.setText("CHICKEN BURGER 100RS");
        nc5.setOpaque(false);
        NONVEGBOX.getContentPane().add(nc5);
        nc5.setBounds(8, 209, 251, 29);

        nc6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nc6.setForeground(new java.awt.Color(255, 255, 255));
        nc6.setText("CHICKEN ROLL 100RS");
        nc6.setOpaque(false);
        NONVEGBOX.getContentPane().add(nc6);
        nc6.setBounds(8, 250, 251, 29);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELECT QUANTITY");
        NONVEGBOX.getContentPane().add(jLabel3);
        jLabel3.setBounds(416, 25, 90, 14);

        nt1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nt1.setText("0");
        NONVEGBOX.getContentPane().add(nt1);
        nt1.setBounds(437, 48, 87, 27);

        nt4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nt4.setText("0");
        nt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nt4ActionPerformed(evt);
            }
        });
        NONVEGBOX.getContentPane().add(nt4);
        nt4.setBounds(437, 163, 87, 27);

        nt5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nt5.setText("0");
        NONVEGBOX.getContentPane().add(nt5);
        nt5.setBounds(437, 210, 87, 27);

        nt6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nt6.setText("0");
        NONVEGBOX.getContentPane().add(nt6);
        nt6.setBounds(437, 250, 85, 27);

        jToggleButton10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton10.setText("DONE");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        NONVEGBOX.getContentPane().add(jToggleButton10);
        jToggleButton10.setBounds(210, 330, 130, 33);
        NONVEGBOX.getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 590, 390);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(300, 500, 900, 600));
        setMinimumSize(new java.awt.Dimension(1035, 650));
        getContentPane().setLayout(null);

        labelname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        labelname.setForeground(new java.awt.Color(255, 255, 255));
        labelname.setText("WELCOME PLACE YOUR ORDER");
        getContentPane().add(labelname);
        labelname.setBounds(110, 20, 578, 39);

        pa4.setBackground(new Color(0,0,0,64));
        pa4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DELIERY DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL");

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DELIERY CHARGES");

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GRAND TOTAL");

        tt1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N

        tt2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N

        tt3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N

        javax.swing.GroupLayout pa4Layout = new javax.swing.GroupLayout(pa4);
        pa4.setLayout(pa4Layout);
        pa4Layout.setHorizontalGroup(
            pa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(pa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        pa4Layout.setVerticalGroup(
            pa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pa4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pa4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(pa4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(tt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(pa4);
        pa4.setBounds(12, 251, 0, 0);

        jToggleButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton7.setText("NON VEG FOOD");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton7);
        jToggleButton7.setBounds(34, 130, 188, 52);

        jToggleButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton8.setText("DRINK");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton8);
        jToggleButton8.setBounds(426, 130, 123, 52);

        pa5.setBackground(new Color(0,0,0,64));
        pa5.setColumns(20);
        pa5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        pa5.setForeground(new java.awt.Color(255, 255, 255));
        pa5.setRows(5);
        pa5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(pa5);
        pa5.setBounds(510, 250, 480, 250);

        jToggleButton9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton9.setText("VEG FOOD");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton9);
        jToggleButton9.setBounds(774, 130, 144, 52);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("TOTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 520, 134, 48);

        jToggleButton11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton11.setText("USERINFO");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton11);
        jToggleButton11.setBounds(774, 13, 144, 46);

        xtext.setText("jTextField1");
        getContentPane().add(xtext);
        xtext.setBounds(22, 26, 38, 20);

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton1.setText("RESET");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(700, 530, 120, 35);

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton2.setText("FINAL");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(900, 530, 89, 35);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("BILL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 530, 81, 35);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 1050, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int A=0;
 int B=0;
 int C=0;
int D=0;
 int E=0;
 int F=0; 
 int A1 =0;
 int B1=0;
 int C1=0;
int D1=0;
 int E1=0;
 int F1=0; 
 int A2=0;
 int B2=0;
 int C2=0;
int D2=0;
 int E2=0;
 int F2=0;
 int z=0;
 int y=80;
 
 int a = Integer.parseInt(nt1.getText());    
 int b = Integer.parseInt(nt2.getText());   
int c = Integer.parseInt(nt3.getText());    
int d = Integer.parseInt(nt4.getText());    
int e = Integer.parseInt(nt5.getText());    
int f = Integer.parseInt(nt6.getText());    
int a1 = Integer.parseInt(rt1.getText());    
 int b1 = Integer.parseInt(rt2.getText());   
int c1 = Integer.parseInt(rt3.getText());    
int d1 = Integer.parseInt(rt4.getText());    
int e1 = Integer.parseInt(rt5.getText());    
int f1 = Integer.parseInt(rt6.getText());    
int a2 = Integer.parseInt(gt1.getText());    
 int b2 = Integer.parseInt(gt2.getText());   
int c2 = Integer.parseInt(gt3.getText());    
int d2 = Integer.parseInt(gt4.getText());    
int e2 = Integer.parseInt(gt5.getText());    
int f2 = Integer.parseInt(gt6.getText());    
 
if (nc1.isSelected())
{A=125*a;}
if(nc2.isSelected())
{B=150*b;}
if (nc3.isSelected())
{C=175*c;}
if(nc4.isSelected())
{D=180*d;}
if (nc5.isSelected())
{E=100*e;}
if(nc6.isSelected())
{F=100*f;}
if (rc1.isSelected())
{A1=100*a1;}
if(rc2.isSelected())
{B1=100*b1;}
if (rc3.isSelected())
{C1=100*c1;}
if(rc4.isSelected())
{D1=50*d1;}
if (rc5.isSelected())
{E1=50*e1;}
if(rc6.isSelected())
{F1=50*f1;}
if (gc1.isSelected())
{A2=100*a2;}
if(gc2.isSelected())
{B2=125*b2;}
if (gc3.isSelected())
{C2=130*c2;}
if(gc4.isSelected())
{D2=125*d2;}
if (gc5.isSelected())
{E2=75*e2;}
if(gc6.isSelected())
{F2=75*f2;}
z=A+B+C+D+E+F+A1+B1+C1+D1+E1+F1+A2+B2+C2+D2+E2+F2;
tt1.setText(""+z);
tt2.setText(""+y+"RS");
int x=y+z;
tt3.setText(""+x);
if(Integer.parseInt(tt1.getText())==0)
    JOptionPane.showMessageDialog(null,"PLEASE ENTER QUANTITY FOR AT LEAST ONE ITEM");

    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String usernm=xtext.getText();
try
{Class.forName("java.sql.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost/classxii","root","system");
 Statement stmt=con.createStatement();
 String query="SELECT * from pass where name='"+usernm+"';";
 ResultSet rs=stmt.executeQuery(query);

 
 while(rs.next())
 { String  name=rs.getString("name");
   int  number=Integer.parseInt(rs.getString("number"));
   String  passw=rs.getString("password");
   String  userid=rs.getString("userid");
   String city=rs.getString("city");
   String address=rs.getString("address");
   int pincode=Integer.parseInt(rs.getString("pincode"));
   infocity.setText(city);
   infoaddress.setText(address);
   infopincode.setText(""+pincode);
   infoname.setText(name);
   infouserid.setText(userid);
   infonumber.setText(""+number);
   
        
 }
}
catch (Exception e)  {
    JOptionPane.showMessageDialog(null,"UNEXPECTED ERROR");}
        int A=0;
 int B=0;
 int C=0;
int D=0;
 int E=0;
 int F=0; 
 int A1 =0;
 int B1=0;
 int C1=0;
int D1=0;
 int E1=0;
 int F1=0; 
 int A2=0;
 int B2=0;
 int C2=0;
int D2=0;
 int E2=0;
 int F2=0;
 int z=0;
 int y=80;

 int a = Integer.parseInt(nt1.getText());    
 int b = Integer.parseInt(nt2.getText());   
int c = Integer.parseInt(nt3.getText());    
int d = Integer.parseInt(nt4.getText());    
int enon = Integer.parseInt(nt5.getText());    
int f = Integer.parseInt(nt6.getText());    
int a1 = Integer.parseInt(rt1.getText());    
 int b1 = Integer.parseInt(rt2.getText());   
int c1 = Integer.parseInt(rt3.getText());    
int d1 = Integer.parseInt(rt4.getText());    
int e1 = Integer.parseInt(rt5.getText());    
int f1 = Integer.parseInt(rt6.getText());    
int a2 = Integer.parseInt(gt1.getText());    
 int b2 = Integer.parseInt(gt2.getText());   
int c2 = Integer.parseInt(gt3.getText());    
int d2 = Integer.parseInt(gt4.getText());    
int e2 = Integer.parseInt(gt5.getText());    
int f2 = Integer.parseInt(gt6.getText());    
 pa5.append("BUYER:-" + infoname.getText());
 pa5.append("\n"+"ADDRESS:-" + infoaddress.getText());
if (a>0)
{A=125*a;
pa5.append("\n"+nc1.getText()+"  *  "+a+"=     "+A);
}
if (b>0)
{B=150*b;
pa5.append("\n"+nc2.getText()+"  *  "+b+"=     "+B);
}
if (c>0)
{C=175*c;
pa5.append("\n"+nc3.getText()+"  *  "+c+"=     "+C);
}
if (d>0)
{D=180*d;
pa5.append("\n"+nc4.getText()+"  *  "+d+"=     "+D);
}
if (enon>0)
{E=100*enon;
pa5.append("\n"+nc5.getText()+"  *  "+enon+"=     "+E);
}
if (f>0)
{F=100*f;
pa5.append("\n"+nc6.getText()+"  *  "+f+"=     "+F);
}
if (a1>0)
{A1=100*a1;
pa5.append("\n"+rc1.getText()+"  *  "+a1+"=     "+A1);
}
if (b1>0)
{B1=100*b1;
pa5.append("\n"+rc2.getText()+"  *  "+b1+"=     "+B1);
}
if (c1>0)
{C1=100*c1;
pa5.append("\n"+rc3.getText()+"  *  "+c1+"=     "+C1);
}
if (d1>0)
{D1=50*d1;
pa5.append("\n"+rc4.getText()+"  *  "+d1+"=     "+D1);
}
if (e1>0)
{E1=50*e1;
pa5.append("\n"+rc5.getText()+"  *  "+e1+"=     "+E1);
}
if (f1>0)
{F1=50*f1;
pa5.append("\n"+rc6.getText()+"  *  "+f1+"=     "+F1);
}
if (a2>0)
{A2=100*a2;
pa5.append("\n"+gc1.getText()+"  *  "+a2+"=     "+A2);
}
if (b2>0)
{B2=125*b2;
pa5.append("\n"+gc2.getText()+"  *  "+b2+"=     "+B2);
}
if (c2>0)
{C2=130*c2;
pa5.append("\n"+gc3.getText()+"  *  "+c2+"=     "+C2);
}
if (d2>0)
{D2=125*d2;
pa5.append("\n"+gc4.getText()+"  *  "+d2+"=     "+D2);
}
if (e2>0)
{E2=75*e2;
pa5.append("\n"+gc5.getText()+"  *  "+e2+"=     "+E2);
}
if (f2>0)
{F2=75*f2;
pa5.append("\n"+gc6.getText()+"  *  "+f2+"=     "+F2);
}
z=A+B+C+D+E+F+A1+B1+C1+D1+E1+F1+A2+B2+C2+D2+E2+F2;
tt1.setText(""+z);
tt2.setText(""+y+"RS");
int x=y+z;
tt3.setText(""+x);
pa5.append("\n"+"DELIVERY CHARGES = 80 RS");
pa5.append("\n"+"TOTAL RS ="+x);
 pa5.append("\n"+"CITY:-" + infocity.getText());
 pa5.append("\n"+"AREA PIN CODE:-" + infopincode.getText());
 pa5.append("\n"+"CONTACT NUMBER:-" + infonumber.getText());
if(Integer.parseInt(tt1.getText())==0)
    JOptionPane.showMessageDialog(null,"PLEASE ENTER QUANTITY FOR AT LEAST ONE ITEM");
 if(Integer.parseInt(tt1.getText())==0)
     tt3.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
nt1.setText("0");
nt2.setText("0");
nt3.setText("0");
nt4.setText("0");
nt5.setText("0");
nt6.setText("0");
gt1.setText("0");
gt2.setText("0");
gt3.setText("0");
gt4.setText("0");
gt5.setText("0");
gt6.setText("0");
rt1.setText("0");
rt2.setText("0");
rt3.setText("0");
rt4.setText("0");
rt5.setText("0");
rt6.setText("0");
tt1.setText("");
tt2.setText("");
tt3.setText("");
pa5.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

        
        
if(Integer.parseInt(tt1.getText())==0)
    JOptionPane.showMessageDialog(null,"PLEASE ENTER QUANTITY FOR AT LEAST ONE ITEM");
else
JOptionPane.showMessageDialog(null,""+infoname.getText()+" YOUR ORDER WILL BE FUILLED WITHIN 30 MINIUTES"+"\n"+"WISHING THAT YOU WILL ENJOY OUR SERVICE");

    

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed




VEGBOX.setVisible(true);



        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed


NONVEGBOX.setVisible(true);






// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed



DRINKBOX.setVisible(true);




        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void nt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nt2ActionPerformed

    private void nt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nt4ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
NONVEGBOX.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
String usernm=xtext.getText();
try
{Class.forName("java.sql.Driver");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost/classxii","root","system");
 Statement stmt=con.createStatement();
 String query="SELECT * from pass where name='"+usernm+"';";
 ResultSet rs=stmt.executeQuery(query);

 
 while(rs.next())
 { String  name=rs.getString("name");
   int  number=Integer.parseInt(rs.getString("number"));
   String  passw=rs.getString("password");
   String  userid=rs.getString("userid");
   String city=rs.getString("city");
   String address=rs.getString("address");
   int pincode=Integer.parseInt(rs.getString("pincode"));
   infocity.setText(city);
   infoaddress.setText(address);
   infopincode.setText(""+pincode);
   infoname.setText(name);
   infouserid.setText(userid);
   infonumber.setText(""+number);
   INFO.setVisible(true);
        
 }
}
catch (Exception e)  {
    JOptionPane.showMessageDialog(null,"UNEXPECTED ERROR");
}

;// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
VEGBOX.setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
DRINKBOX.setVisible(false);            // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DRINKBOX;
    private javax.swing.JFrame INFO;
    private javax.swing.JFrame NONVEGBOX;
    private javax.swing.JFrame VEGBOX;
    private javax.swing.JCheckBox gc1;
    private javax.swing.JCheckBox gc2;
    private javax.swing.JCheckBox gc3;
    private javax.swing.JCheckBox gc4;
    private javax.swing.JCheckBox gc5;
    private javax.swing.JCheckBox gc6;
    private javax.swing.JTextField gt1;
    private javax.swing.JTextField gt2;
    private javax.swing.JTextField gt3;
    private javax.swing.JTextField gt4;
    private javax.swing.JTextField gt5;
    private javax.swing.JTextField gt6;
    private javax.swing.JLabel infoaddress;
    private javax.swing.JLabel infocity;
    private javax.swing.JLabel infoname;
    private javax.swing.JLabel infonumber;
    private javax.swing.JLabel infopincode;
    private javax.swing.JLabel infouserid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel labelname;
    private javax.swing.JCheckBox nc1;
    private javax.swing.JCheckBox nc2;
    private javax.swing.JCheckBox nc3;
    private javax.swing.JCheckBox nc4;
    private javax.swing.JCheckBox nc5;
    private javax.swing.JCheckBox nc6;
    private javax.swing.JTextField nt1;
    private javax.swing.JTextField nt2;
    private javax.swing.JTextField nt3;
    private javax.swing.JTextField nt4;
    private javax.swing.JTextField nt5;
    private javax.swing.JTextField nt6;
    private javax.swing.JPanel pa4;
    private javax.swing.JTextArea pa5;
    private javax.swing.JCheckBox rc1;
    private javax.swing.JCheckBox rc2;
    private javax.swing.JCheckBox rc3;
    private javax.swing.JCheckBox rc4;
    private javax.swing.JCheckBox rc5;
    private javax.swing.JCheckBox rc6;
    private javax.swing.JTextField rt1;
    private javax.swing.JTextField rt2;
    private javax.swing.JTextField rt3;
    private javax.swing.JTextField rt4;
    private javax.swing.JTextField rt5;
    private javax.swing.JTextField rt6;
    private javax.swing.JTextField tt1;
    private javax.swing.JTextField tt2;
    private javax.swing.JTextField tt3;
    private javax.swing.JTextField xtext;
    // End of variables declaration//GEN-END:variables
}
