/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodbookingproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author sujatha
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();this.setBounds(200,50,1100,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JFrame();
        addresstext = new javax.swing.JTextField();
        passtext = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pincodetext = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        srno = new javax.swing.JTextField();
        useridtext = new javax.swing.JTextField();
        citytext = new javax.swing.JTextField();
        numbertext = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        admin.setLocation(new java.awt.Point(100, 50));
        admin.setMinimumSize(new java.awt.Dimension(600, 550));
        admin.getContentPane().setLayout(null);

        addresstext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        addresstext.setEnabled(false);
        addresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstextActionPerformed(evt);
            }
        });
        admin.getContentPane().add(addresstext);
        addresstext.setBounds(311, 230, 230, 27);

        passtext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        passtext.setEnabled(false);
        admin.getContentPane().add(passtext);
        passtext.setBounds(311, 380, 230, 27);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("ENTER YOUR FULL ADDRESS");
        admin.getContentPane().add(jLabel22);
        jLabel22.setBounds(10, 240, 320, 22);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("ENTER CITY");
        admin.getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 280, 219, 22);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("SR NUMBER");
        admin.getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 40, 135, 22);

        pincodetext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        pincodetext.setEnabled(false);
        admin.getContentPane().add(pincodetext);
        pincodetext.setBounds(311, 320, 230, 27);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("ENTER YOUR PHONE NUMBER");
        admin.getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 140, 274, 22);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("ENTER AREA PIN CODE");
        admin.getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 330, 253, 22);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("ENTER USER ID");
        admin.getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 190, 243, 22);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("ENTER PASSWORD");
        admin.getContentPane().add(jLabel20);
        jLabel20.setBounds(10, 380, 165, 22);

        srno.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        admin.getContentPane().add(srno);
        srno.setBounds(160, 40, 161, 27);

        useridtext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        useridtext.setEnabled(false);
        admin.getContentPane().add(useridtext);
        useridtext.setBounds(311, 180, 230, 27);

        citytext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        citytext.setEnabled(false);
        admin.getContentPane().add(citytext);
        citytext.setBounds(311, 280, 230, 27);

        numbertext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        numbertext.setEnabled(false);
        admin.getContentPane().add(numbertext);
        numbertext.setBounds(311, 140, 230, 27);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("ENTER YOUR FULL NAME");
        admin.getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 100, 270, 22);

        nametext.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        nametext.setEnabled(false);
        admin.getContentPane().add(nametext);
        nametext.setBounds(311, 90, 230, 27);

        jToggleButton3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jToggleButton3.setText("SEARCH");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(320, 40, 100, 30);

        jToggleButton4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jToggleButton4.setText("UPDATE");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(90, 440, 130, 40);

        jToggleButton5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jToggleButton5.setText("DELETE");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jToggleButton5);
        jToggleButton5.setBounds(270, 440, 120, 40);
        admin.getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 120, 490, 310);

        jToggleButton6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jToggleButton6.setText("CLEAR");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jToggleButton6);
        jToggleButton6.setBounds(460, 40, 100, 30);
        admin.getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 30, 150, 0);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        admin.getContentPane().add(jButton1);
        jButton1.setBounds(440, 440, 90, 40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jToggleButton1.setText("ADMIN");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 135, 58));

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jToggleButton2.setText("CUSTOMER");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 143, 58));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ONLINE FOOD BOOKING SYSTEM MADE BY ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 830, 41));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PILLA VAISHNO MOHAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 590, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USER WINDOW");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 470, 110));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

new NewJFrame11().setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

admin.setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
int SRNO=Integer.parseInt(srno.getText());
try
    {  Class.forName("java.sql.Driver");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/classxii","root","system");
       Statement stmt=con.createStatement();
       String query="SELECT * from pass where sr_no="+SRNO+";";
       ResultSet rs=stmt.executeQuery(query);  
       while(rs.next())
       { String  name=rs.getString("name");
         int  number=Integer.parseInt(rs.getString("number"));
         String  passw=rs.getString("password");
         String  userid=rs.getString("userid");
         String city=rs.getString("city");
         String address=rs.getString("address");
         int pincode=Integer.parseInt(rs.getString("pincode"));
         passtext.setText(passw);
         pincodetext.setText(""+pincode);
         useridtext.setText(userid);
         numbertext.setText(""+number);
         nametext.setText(name);
         citytext.setText(city);
         addresstext.setText(address);
         addresstext.setEnabled(true);
         passtext.setEnabled(true);
         nametext.setEnabled(true);
         useridtext.setEnabled(true);
         pincodetext.setEnabled(true);
         numbertext.setEnabled(true);
         citytext.setEnabled(true);
        }
    }
catch (Exception e) 
    {JOptionPane.showMessageDialog(null,"UNEXPECTED ERROR");} 
if(nametext.getText().equals(""))
JOptionPane.showMessageDialog(null,"SORRY NO SUCH RECORD EXISTS");
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
       
int SRNO=Integer.parseInt(srno.getText());
String NEWNAME=nametext.getText();
String NEWCITY=citytext.getText();
String NEWADDRESS=addresstext.getText();
int NEWPINCODE=Integer.parseInt(pincodetext.getText());
int NEWNUMBER=Integer.parseInt(numbertext.getText());
String NEWUSERID=useridtext.getText();
String NEWPASS= new String(passtext.getPassword());
try
{  Class.forName("java.sql.Driver");
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost/classxii","root","system");
   Statement stmt=con.createStatement();
   String query=
   "update pass set name='"+NEWNAME+"',city='"+NEWCITY+"',address='"+NEWADDRESS+"',pincode="+NEWPINCODE+",number="+NEWNUMBER+",password='"+NEWPASS+"' WHERE sr_no="+SRNO+";";
   stmt.executeUpdate(query);
   JOptionPane.showMessageDialog(null,"RECORD SUCCESSFULLY UPDATED");
   passtext.setText("");
   pincodetext.setText("");
   useridtext.setText("");
   numbertext.setText("");
   nametext.setText("");
   citytext.setText("");
   addresstext.setText("");
   srno.setText("");
}
catch (Exception e)  
{JOptionPane.showMessageDialog(null,"UNEXPECTED ERROR");} 
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed

try
{ Class.forName("java.sql.Driver");
  Connection con=DriverManager.getConnection("jdbc:mysql://localhost/classxii","root","system");
  Statement stmt=con.createStatement();
  String query="delete from pass where sr_no="+srno.getText()+";";
  stmt.executeUpdate(query);
  JOptionPane.showMessageDialog(null,"RECORD SUCCESSFULLY DELETED");

}
catch (Exception e)  
{JOptionPane.showMessageDialog(null,"UNEXPECTED ERROR");}  

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void addresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addresstextActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
 passtext.setText("");
 pincodetext.setText("");
 useridtext.setText("");
 numbertext.setText("");
 nametext.setText("");
 citytext.setText("");
 addresstext.setText("");
 srno.setText("");




        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new NewJFrame().setVisible(true);
admin.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.JFrame admin;
    private javax.swing.JTextField citytext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField numbertext;
    private javax.swing.JPasswordField passtext;
    private javax.swing.JTextField pincodetext;
    private javax.swing.JTextField srno;
    private javax.swing.JTextField useridtext;
    // End of variables declaration//GEN-END:variables
}
