/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodbookingproject;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.DriverManager;
/**
 *
 * @author sujatha
 */
public class NewJFrame11 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame11() {
        initComponents();this.setBounds(300,100,750,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        paswd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        id.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        getContentPane().add(id);
        id.setBounds(330, 110, 400, 27);

        jToggleButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton4.setText("LOGIN");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(340, 240, 99, 41);

        jLabel15.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ENTER USER ID");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(60, 110, 161, 21);

        jLabel16.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENTER PASSWORD");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(50, 190, 190, 21);

        jToggleButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jToggleButton5.setText("NEW USER");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton5);
        jToggleButton5.setBounds(330, 310, 128, 46);

        paswd.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        getContentPane().add(paswd);
        paswd.setBounds(330, 180, 400, 27);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 370, 90, 40);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN PAGE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 10, 360, 70);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        String usernm=id.getText();
        String pass=new String(paswd.getPassword());
        String admin= "power";
        String DEVNAME="VAISHNO MOHAN";
        try
        {  Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/classxii","root","system");
           Statement stmt=con.createStatement();
           String query="SELECT * from pass where userid='"+usernm+"';";
           ResultSet rs=stmt.executeQuery(query);
           if(pass.equals(admin))
               {JOptionPane.showMessageDialog(null,"WELCOME ADMINISTRATOR");
                   new NewJFrame8(DEVNAME).setVisible(true);this.dispose();
                   }
           else{}
           while (rs.next())
           { String  name=rs.getString("name");
            int  number=Integer.parseInt(rs.getString("number"));
            String  passw=rs.getString("password");
            String  userid=rs.getString("userid");
            if (pass.equals(passw) && userid.equals(usernm))
            {new NewJFrame8(name).setVisible(true);
             JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL");
             this.dispose();
             break;}
            else
            {JOptionPane.showMessageDialog(null,"INVALID USERNAME AND PASSWORD");
                    break;}
            }
        }
        catch (Exception e)  {
            JOptionPane.showMessageDialog
            (null,"UNEXPECTED ERROR");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
new NewJFrame1().setVisible(true);this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new NewJFrame().setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JPasswordField paswd;
    // End of variables declaration//GEN-END:variables
}
